name: 'Cloud Builder Pulumi'
description: 'build'
inputs:
  type:  # type
    description: 'cloud builder action type'
    required: true
  username:  # github user
    description: 'github username'
    required: true
  email: # email
    description: 'email'
    required: true
  environment:  # stage, prod
    description: 'environment'
    required: true
  repo-location:  # repo location
    description: 'repo location'
    required: true
  command:
    description: 'command up/destroy/preview'
    required: false
    default: 'preview' 
  app-name:
    description: 'application name'
    required: true
  url-endpoint:
    description: 'url endpoint'
    required: false
    default: ''
  github-token:  # github token
    description: 'github token'
    required: true
  metadata: # dynamic data
    description: 'dynamic metadata'
    required: false
outputs:
  time: # output will be available to future steps
    description: 'The current time after waiting'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding: 
  icon: 'cloud-snow'
  color: 'purple' 
