name: 'Cloud Builder Pulumi'
description: 'Wait a designated number of milliseconds'
inputs:
  milliseconds:  # id of input
    description: 'number of milliseconds to wait'
    required: false
    default: '1000'
  type:  # type
    description: 'cloud builder action type'
    required: true
  user:  # user id
    description: 'user toretrieve configs'
    required: true
  username:  # github user
    description: 'github username'
    required: true
  password:  # github password
    description: 'github password'
    required: true
  org_name:  # github password
    description: 'org name'
    required: true
  project_name:  # github password
    description: 'project name'
    required: true
  repo:  # github password
    description: 'repo'
    required: true
outputs:
  time: # output will be available to future steps
    description: 'The current time after waiting'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding: 
  icon: 'cloud-snow'
  color: 'purple' 
